(function (_$cont) {
  (function (_$cont) {
    try {
      setTimeout(function () {
        try {
          throw new Error('my error');
          _$cont();
        } catch (_$err) {
          _$cont(_$err);
        }
      }, 200);
    } catch (_$err) {
      _$cont(_$err);
    }
  }(function (err) {
    if (err !== undefined) {
      console.log('Error caught:');
      setTimeout(function () {
        console.log(err);
        _$cont();
      }, 1000);
    } else
      _$cont();
  }));
}(function () {
  console.log('Finally');
  console.log('Done');
}));
/* Generated by Continuation.js v0.1.1 */